
package ki;

import javax.swing.JFrame;

public class GUIdesRPE extends javax.swing.JFrame {

    EmbedMessage embed;
    ExtractMessage extract;
    GUIMainMenu menu;
    
    /**
     * Creates new form MainMenu
     */
    public GUIdesRPE() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hidingButton = new javax.swing.JButton();
        extractButton = new javax.swing.JButton();
        steganographyLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kombinasi Algoritma DES dengan RPE");
        getContentPane().setLayout(null);

        hidingButton.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        hidingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ki/icons8-append-clip-50.png"))); // NOI18N
        hidingButton.setText(" Sisipkan Pesan");
        hidingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidingButtonMouseClicked(evt);
            }
        });
        hidingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hidingButton);
        hidingButton.setBounds(420, 230, 550, 80);

        extractButton.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        extractButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ki/icons8-paper-plane-50.png"))); // NOI18N
        extractButton.setText(" Ekstrak Pesan");
        extractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractButtonActionPerformed(evt);
            }
        });
        getContentPane().add(extractButton);
        extractButton.setBounds(420, 340, 550, 80);

        steganographyLabel.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        steganographyLabel.setForeground(new java.awt.Color(204, 204, 204));
        steganographyLabel.setText("Kombinasi DES dengan RPE");
        getContentPane().add(steganographyLabel);
        steganographyLabel.setBounds(350, 130, 700, 60);

        backBtn.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ki/icons8-reply-arrow-50.png"))); // NOI18N
        backBtn.setText(" Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(420, 450, 550, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ki/desktop-1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, -30, 1400, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hidingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidingButtonActionPerformed
        EmbedMessage embed=new EmbedMessage();
        embed.setVisible(true);
    }//GEN-LAST:event_hidingButtonActionPerformed

    private void extractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractButtonActionPerformed
        ExtractMessage extract=new ExtractMessage();
        extract.setVisible(true);
    }//GEN-LAST:event_extractButtonActionPerformed

    private void hidingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidingButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hidingButtonMouseClicked

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        GUIMainMenu menu = new GUIMainMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIdesRPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIdesRPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIdesRPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIdesRPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIdesRPE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton extractButton;
    private javax.swing.JButton hidingButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel steganographyLabel;
    // End of variables declaration//GEN-END:variables
}
