package ki;

import javax.swing.JFrame;

public class GUIMainMenu extends javax.swing.JFrame {

    GUIdesRPE lsbrpe;
    
    /**
     * Creates new form MainMenu
     */
    public GUIMainMenu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hidingButton = new javax.swing.JButton();
        steganographyLabel = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tugas Besar KI Steganography\n");
        getContentPane().setLayout(null);

        hidingButton.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        hidingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ki/icons8-remove-key-50.png"))); // NOI18N
        hidingButton.setText(" Kombinasi DES dengan RPE");
        hidingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidingButtonMouseClicked(evt);
            }
        });
        hidingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hidingButton);
        hidingButton.setBounds(380, 290, 631, 90);

        steganographyLabel.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        steganographyLabel.setForeground(new java.awt.Color(204, 204, 204));
        steganographyLabel.setText("STEGANOGRAFI");
        getContentPane().add(steganographyLabel);
        steganographyLabel.setBounds(480, 200, 470, 57);

        exitBtn.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ki/icons8-logout-50.png"))); // NOI18N
        exitBtn.setText("Keluar");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn);
        exitBtn.setBounds(380, 400, 631, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ki/desktop-1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-50, -40, 1430, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hidingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidingButtonActionPerformed
        GUIdesRPE desrpe = new GUIdesRPE();
        desrpe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hidingButtonActionPerformed

    private void hidingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidingButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hidingButtonMouseClicked

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton hidingButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel steganographyLabel;
    // End of variables declaration//GEN-END:variables
}
